### ISSUE TITLE
22 Edge Detector HLS showing errors

### ISSUE THREAD

**Issue by Nrusinga** [hlslibs/matchlib_toolkit#1]
Hello,

I wanted to run HLS in this project( Edge Detector), but it threw some errors stating "dy_chan not defined". Could you please look at and let me know the solution.

I have attached snapshot of it.

Thanks,
Charan
<img width="1416" alt="Screenshot 2023-08-14 at 12 28 41 PM" src="https://github.com/hlslibs/matchlib_toolkit/assets/48976841/c57c67e4-112c-49ea-883c-2941d7038841">

**Comment by Stuart-Swan** [comment]
I think you need to upgrade to a newer version of Catapult, at least released in 2023.

**Comment by Nrusinga** [comment]
Indeed, I eventually obtained the updated version from the GitHub repository, and it did work. I appreciate your assistance nonetheless.

Charan
