### ISSUE TITLE
10_fifo_channel_hier: Issues in command "make build"

### ISSUE THREAD

**Issue by Nrusinga** [hlslibs/matchlib_toolkit#2]
Hello,
When I tried to run the make build command in this directory it says, fifo1 is undefined. mc_fifo.h in the correct directory as well. 
I have attached the snapshot, could you please look into it?

Best,
Charan
<img width="731" alt="Screenshot 2023-08-14 at 1 04 36 PM" src="https://github.com/hlslibs/matchlib_toolkit/assets/48976841/59d3e2e9-bb7b-4f70-9f47-7a8d6ccf4eae">

**Comment by Stuart-Swan** [comment]
I think you need to upgrade to a newer version of Catapult, at least released in 2023.
Alternatively you can use the fully self-contained standalone kit here:

https://forums.accellera.org/files/file/126-matchlib-examples-kit-for-accellera-systemc-evolution-day-2020-presentation/

**Comment by Nrusinga** [comment]
This worked too. Thanks 


Charan
